// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace testing.Features
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Login and Order from Sauce Demo Website")]
    public partial class LoginAndOrderFromSauceDemoWebsiteFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
#line 1 "WebApps.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Features", "Login and Order from Sauce Demo Website", "A short summary of the feature", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<NUnit.Framework.TestContext>(NUnit.Framework.TestContext.CurrentContext);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("1. Logging in without password (Negative Test Case 1)")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _1_LoggingInWithoutPasswordNegativeTestCase1(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("1. Logging in without password (Negative Test Case 1)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 36
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 37
 testRunner.Given(string.Format("User Navigates to {0}", url), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 38
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_usernname\'", username), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 39
 testRunner.And("User Clicks on \'sauceDemo_loginBtn\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 40
 testRunner.Then("\'sauceDemo_loginError\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 41
 testRunner.Then("User Clicks on \'sauceDemo_loginErrorBtn\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("2. Logging into Sauce Demo Website")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _2_LoggingIntoSauceDemoWebsite(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("2. Logging into Sauce Demo Website", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 45
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 46
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_usernname\'", username), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 47
 testRunner.Then(string.Format("User Enters {0} in \'sauceDemo_password\'", password), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 48
 testRunner.And("User Clicks on \'sauceDemo_loginBtn\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 49
 testRunner.Then("\'sauceDemo_appLogo\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("3. Ordering an item from the Sauce Demo Website")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _3_OrderingAnItemFromTheSauceDemoWebsite(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("3. Ordering an item from the Sauce Demo Website", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 52
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 53
 testRunner.When("User Clicks on \'sauceDemo_addToCartBtn\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 54
 testRunner.And("User Clicks on \'sauceDemo_shoppingCart\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 55
 testRunner.And("User Clicks on \'sauceDemo_checkoutButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 58
 testRunner.Then("\'sauceDemo_continueButton\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("4. Enter Wrong Details (Negative Test case 2)")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _4_EnterWrongDetailsNegativeTestCase2(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("4. Enter Wrong Details (Negative Test case 2)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 61
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 62
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_firstNameInputField\'", firstName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 63
 testRunner.And("User Clicks on \'sauceDemo_continueButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 66
 testRunner.Then("\'sauceDemo_errorButton\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 68
 testRunner.Then("User Clicks on \'sauceDemo_errorButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("5. Enter Wrong Details (Negative Test case 3)")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _5_EnterWrongDetailsNegativeTestCase3(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("5. Enter Wrong Details (Negative Test case 3)", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 71
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 72
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_firstNameInputField\'", firstName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 73
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_LastNameInputField\'", lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 74
 testRunner.And("User Clicks on \'sauceDemo_continueButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 77
 testRunner.Then("\'sauceDemo_errorButton\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
#line 79
 testRunner.Then("User Clicks on \'sauceDemo_errorButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("6. Enter user details and checkout")]
        [NUnit.Framework.CategoryAttribute("DataSource:testData/sauceDemo.xlsx")]
        [NUnit.Framework.TestCaseAttribute("sauceDemo", "https://www.saucedemo.com/", "standard_user", "secret_sauce", "Aman", "Alam", "12345", "", "", "", "", "", ".", null)]
        public void _6_EnterUserDetailsAndCheckout(string websiteName, string url, string username, string password, string firstName, string lastName, string postalCode, string column7, string column8, string column9, string column10, string column11, string _, string[] exampleTags)
        {
            string[] @__tags = new string[] {
                    "DataSource:testData/sauceDemo.xlsx"};
            if ((exampleTags != null))
            {
                @__tags = System.Linq.Enumerable.ToArray(System.Linq.Enumerable.Concat(@__tags, exampleTags));
            }
            string[] tagsOfScenario = @__tags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("websiteName", websiteName);
            argumentsOfScenario.Add("url", url);
            argumentsOfScenario.Add("username", username);
            argumentsOfScenario.Add("password", password);
            argumentsOfScenario.Add("firstName", firstName);
            argumentsOfScenario.Add("lastName", lastName);
            argumentsOfScenario.Add("postalCode", postalCode);
            argumentsOfScenario.Add("Column7", column7);
            argumentsOfScenario.Add("Column8", column8);
            argumentsOfScenario.Add("Column9", column9);
            argumentsOfScenario.Add("Column10", column10);
            argumentsOfScenario.Add("Column11", column11);
            argumentsOfScenario.Add(".", _);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("6. Enter user details and checkout", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 82
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 83
 testRunner.When(string.Format("User Enters {0} in \'sauceDemo_firstNameInputField\'", firstName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line hidden
#line 84
 testRunner.And(string.Format("User Enters {0} in \'sauceDemo_LastNameInputField\'", lastName), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 85
 testRunner.And(string.Format("User Enters {0} in \'sauceDemo_postalCodeInputField\'", postalCode), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 86
 testRunner.And("User Clicks on \'sauceDemo_continueButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 87
 testRunner.And("User Clicks on \'sauceDemo_finishButton\'", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
#line 90
 testRunner.Then("\'sauceDemo_thankYouHeader\' should be visible", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
